### ISSUE TITLE
Lights are not working on IDG-A33X

### ISSUE THREAD

**Issue by andrewjoseofficial** [Octal450/IDG-A33X#12]
### General
----

I am submitting a: (select one) 
* [x] Bug report
* [ ] Feature request

### Details
When I turned on the logo lights and the wing lights in the overhead panel, and looked at the external side of the plane, I noticed no logo light was working nor was there a wing light working.
----
#### Expected Behavior (bug reports)
The lights shouldn't seem visible on the plane exterior when you turn it on in the overhead panel.

#### Requested Behavior  (feature requests)
The lights are visible on the exterior of the plane at night, just like that of A32X and 777s.

#### Possible Solution (if applicable)
I don't know much about code, because I only make youtube movies of my Flightgear flights.

#### Steps to Reproduce (bug reports)

1.  Change time to night
2. Turn all external lights in the overhead panel
3. Notice that except landing lights no other lights illuminate the plane

**Comment by legoboyvdlp** [comment]
Known issue, unable to be fixed for now, sorry. I have no idea why it is not working, everything seems right but it doesn't work.

**Comment by Octal450** [comment]
Yes. We will re-structure the models in the future which should fix it. For now, it's not implemented sorry.

Kind Regards,
Josh
